# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '32 9 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is still waiting on a response, and will be closed soon if there is no response.'
        stale-pr-message: 'This PR is still waiting on updates and will be closed soon if there is no update.'
        stale-issue-label: 'closing-soon-if-no-response'
        stale-pr-label: 'closing-soon-if-no-response'
        days-before-stale: 7
        days-before-close: 2
        days-before-pr-stale: 30
        days-before-pr-close: 7
        any-of-labels: response-needed,changes-requested
